import { DEFAULT_THETA_E_C } from "@/engine/types"

import type { WizardRoomInput, WizardState } from "./types"

const room = (
  input: Omit<WizardRoomInput, "roofWindowAreaM2" | "hasEntranceDoor"> &
    Partial<Pick<WizardRoomInput, "roofWindowAreaM2" | "hasEntranceDoor">>,
): WizardRoomInput => ({
  roofWindowAreaM2: 0,
  hasEntranceDoor: false,
  ...input,
})

export function exampleWizardState(): WizardState {
  return {
    step: 3,
    projectName: "ID_115986",
    address: "",
    buildingKind: "dhh",
    era: "altbau",
    windowsReplaced: true,
    hasMvhr: false,
    plzOrCity: "",
    thetaEC: DEFAULT_THETA_E_C,
    thetaEManual: false,
    storeys: [
      {
        id: "EG",
        label: "Erdgeschoss",
        heightM: 2.38,
        below: "keller-unbeheizt",
        above: "beheizt",
      },
      {
        id: "OG1",
        label: "Obergeschoss",
        heightM: 2.38,
        below: "beheizt",
        above: "beheizt",
      },
      {
        id: "DG",
        label: "Dachgeschoss",
        heightM: 1.86,
        below: "beheizt",
        above: "dachschraegen",
        kniestockM: 0.42,
        firstM: 3.3,
      },
    ],
    rooms: [
      room({
        key: "demo-dg-r1",
        storeyId: "DG",
        name: "Wohnraum Dach",
        roomType: "Dach",
        widthM: 5.57,
        lengthM: 6.6,
        walls: [{ orientation: "W", lengthM: 8.92, windowAreaM2: 0.6 }],
        roofWidthM: 13.2,
        roofLengthM: 4.02,
        roofWindowAreaM2: 1.8,
        partyWallLengthM: 8.92,
      }),
      room({
        key: "demo-og1-r1",
        storeyId: "OG1",
        name: "Schlafen",
        roomType: "Schlafen",
        widthM: 3.24,
        lengthM: 4.2,
        walls: [{ orientation: "N", lengthM: 3.58, windowAreaM2: 1.0 }],
        roofWidthM: 0,
        roofLengthM: 0,
        partyWallLengthM: 4.45,
      }),
      room({
        key: "demo-og1-r2",
        storeyId: "OG1",
        name: "Schlafen 2",
        roomType: "Schlafen",
        widthM: 3.28,
        lengthM: 4.2,
        walls: [
          { orientation: "N", lengthM: 3.83, windowAreaM2: 0 },
          { orientation: "W", lengthM: 3.87, windowAreaM2: 1.5 },
        ],
        roofWidthM: 0,
        roofLengthM: 0,
        partyWallLengthM: 4.45,
      }),
      room({
        key: "demo-og1-r3",
        storeyId: "OG1",
        name: "Bad/Dusche/Umkl.",
        roomType: "Bad",
        widthM: 3.7,
        lengthM: 3.12,
        walls: [{ orientation: "S", lengthM: 1.29, windowAreaM2: 1.03 }],
        roofWidthM: 0,
        roofLengthM: 0,
        partyWallLengthM: 2.88,
      }),
      room({
        key: "demo-og1-r5",
        storeyId: "OG1",
        name: "Abstellraum",
        roomType: "Abstellraum",
        widthM: 1.83,
        lengthM: 3.45,
        walls: [{ orientation: "S", lengthM: 3.15, windowAreaM2: 1.5 }],
        roofWidthM: 0,
        roofLengthM: 0,
        partyWallLengthM: 1.67,
      }),
      room({
        key: "demo-eg-r1",
        storeyId: "EG",
        name: "Wohnraum",
        roomType: "Wohnraum",
        widthM: 4.11,
        lengthM: 6.67,
        walls: [
          { orientation: "N", lengthM: 7.27, windowAreaM2: 3.4 },
          { orientation: "W", lengthM: 4.37, windowAreaM2: 1.6 },
        ],
        roofWidthM: 0,
        roofLengthM: 0,
        partyWallLengthM: 4.37,
      }),
      room({
        key: "demo-eg-r2",
        storeyId: "EG",
        name: "Essen",
        roomType: "Essen",
        widthM: 5.13,
        lengthM: 3.24,
        walls: [{ orientation: "W", lengthM: 1.7, windowAreaM2: 1.4 }],
        roofWidthM: 0,
        roofLengthM: 0,
        partyWallLengthM: 5.18,
      }),
      room({
        key: "demo-eg-r4",
        storeyId: "EG",
        name: "WC-Raum",
        roomType: "WC",
        widthM: 1.8,
        lengthM: 2.18,
        walls: [
          { orientation: "W", lengthM: 3.04, windowAreaM2: 0 },
          { orientation: "S", lengthM: 1.6, windowAreaM2: 0.5 },
        ],
        roofWidthM: 0,
        roofLengthM: 0,
        partyWallLengthM: 3.04,
      }),
      room({
        key: "demo-eg-r5",
        storeyId: "EG",
        name: "Wohnraum 2",
        roomType: "Wohnraum",
        widthM: 3.23,
        lengthM: 4.47,
        walls: [{ orientation: "W", lengthM: 3.71, windowAreaM2: 2.6 }],
        roofWidthM: 0,
        roofLengthM: 0,
        partyWallLengthM: 6.86,
      }),
      room({
        key: "demo-eg-r6",
        storeyId: "EG",
        name: "Wohnraum 3",
        roomType: "Wohnraum",
        widthM: 3.23,
        lengthM: 4.52,
        walls: [
          { orientation: "W", lengthM: 4.46, windowAreaM2: 1.3 },
          { orientation: "S", lengthM: 3.86, windowAreaM2: 0 },
        ],
        roofWidthM: 0,
        roofLengthM: 0,
        partyWallLengthM: 4.97,
      }),
    ],
    presetOverrides: {},
  }
}
